// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_coordinator_messages.proto
// Protobuf Java Version: 4.26.1
package com.javasteam.protobufs;

public final class GameCoordinatorMessages {
  private GameCoordinatorMessages() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        GameCoordinatorMessages.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(GameCoordinatorMessages.msgpoolSoftLimit);
    registry.add(GameCoordinatorMessages.msgpoolHardLimit);
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  /** Protobuf enum {@code GCProtoBufMsgSrc} */
  public enum GCProtoBufMsgSrc implements com.google.protobuf.ProtocolMessageEnum {
    /** <code>GCProtoBufMsgSrc_Unspecified = 0;</code> */
    GCProtoBufMsgSrc_Unspecified(0),
    /** <code>GCProtoBufMsgSrc_FromSystem = 1;</code> */
    GCProtoBufMsgSrc_FromSystem(1),
    /** <code>GCProtoBufMsgSrc_FromSteamID = 2;</code> */
    GCProtoBufMsgSrc_FromSteamID(2),
    /** <code>GCProtoBufMsgSrc_FromGC = 3;</code> */
    GCProtoBufMsgSrc_FromGC(3),
    /** <code>GCProtoBufMsgSrc_ReplySystem = 4;</code> */
    GCProtoBufMsgSrc_ReplySystem(4),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          GCProtoBufMsgSrc.class.getName());
    }

    /** <code>GCProtoBufMsgSrc_Unspecified = 0;</code> */
    public static final int GCProtoBufMsgSrc_Unspecified_VALUE = 0;

    /** <code>GCProtoBufMsgSrc_FromSystem = 1;</code> */
    public static final int GCProtoBufMsgSrc_FromSystem_VALUE = 1;

    /** <code>GCProtoBufMsgSrc_FromSteamID = 2;</code> */
    public static final int GCProtoBufMsgSrc_FromSteamID_VALUE = 2;

    /** <code>GCProtoBufMsgSrc_FromGC = 3;</code> */
    public static final int GCProtoBufMsgSrc_FromGC_VALUE = 3;

    /** <code>GCProtoBufMsgSrc_ReplySystem = 4;</code> */
    public static final int GCProtoBufMsgSrc_ReplySystem_VALUE = 4;

    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static GCProtoBufMsgSrc valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GCProtoBufMsgSrc forNumber(int value) {
      switch (value) {
        case 0:
          return GCProtoBufMsgSrc_Unspecified;
        case 1:
          return GCProtoBufMsgSrc_FromSystem;
        case 2:
          return GCProtoBufMsgSrc_FromSteamID;
        case 3:
          return GCProtoBufMsgSrc_FromGC;
        case 4:
          return GCProtoBufMsgSrc_ReplySystem;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GCProtoBufMsgSrc> internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<GCProtoBufMsgSrc>
        internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<GCProtoBufMsgSrc>() {
              public GCProtoBufMsgSrc findValueByNumber(int number) {
                return GCProtoBufMsgSrc.forNumber(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
      return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
      return GameCoordinatorMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final GCProtoBufMsgSrc[] VALUES = values();

    public static GCProtoBufMsgSrc valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GCProtoBufMsgSrc(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GCProtoBufMsgSrc)
  }

  public interface CMsgProtoBufHeaderOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:CMsgProtoBufHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional fixed64 client_steam_id = 1;</code>
     *
     * @return Whether the clientSteamId field is set.
     */
    boolean hasClientSteamId();

    /**
     * <code>optional fixed64 client_steam_id = 1;</code>
     *
     * @return The clientSteamId.
     */
    long getClientSteamId();

    /**
     * <code>optional int32 client_session_id = 2;</code>
     *
     * @return Whether the clientSessionId field is set.
     */
    boolean hasClientSessionId();

    /**
     * <code>optional int32 client_session_id = 2;</code>
     *
     * @return The clientSessionId.
     */
    int getClientSessionId();

    /**
     * <code>optional uint32 source_app_id = 3;</code>
     *
     * @return Whether the sourceAppId field is set.
     */
    boolean hasSourceAppId();

    /**
     * <code>optional uint32 source_app_id = 3;</code>
     *
     * @return The sourceAppId.
     */
    int getSourceAppId();

    /**
     * <code>optional fixed64 job_id_source = 10 [default = 18446744073709551615];</code>
     *
     * @return Whether the jobIdSource field is set.
     */
    boolean hasJobIdSource();

    /**
     * <code>optional fixed64 job_id_source = 10 [default = 18446744073709551615];</code>
     *
     * @return The jobIdSource.
     */
    long getJobIdSource();

    /**
     * <code>optional fixed64 job_id_target = 11 [default = 18446744073709551615];</code>
     *
     * @return Whether the jobIdTarget field is set.
     */
    boolean hasJobIdTarget();

    /**
     * <code>optional fixed64 job_id_target = 11 [default = 18446744073709551615];</code>
     *
     * @return The jobIdTarget.
     */
    long getJobIdTarget();

    /**
     * <code>optional string target_job_name = 12;</code>
     *
     * @return Whether the targetJobName field is set.
     */
    boolean hasTargetJobName();

    /**
     * <code>optional string target_job_name = 12;</code>
     *
     * @return The targetJobName.
     */
    String getTargetJobName();

    /**
     * <code>optional string target_job_name = 12;</code>
     *
     * @return The bytes for targetJobName.
     */
    com.google.protobuf.ByteString getTargetJobNameBytes();

    /**
     * <code>optional int32 eresult = 13 [default = 2];</code>
     *
     * @return Whether the eresult field is set.
     */
    boolean hasEresult();

    /**
     * <code>optional int32 eresult = 13 [default = 2];</code>
     *
     * @return The eresult.
     */
    int getEresult();

    /**
     * <code>optional string error_message = 14;</code>
     *
     * @return Whether the errorMessage field is set.
     */
    boolean hasErrorMessage();

    /**
     * <code>optional string error_message = 14;</code>
     *
     * @return The errorMessage.
     */
    String getErrorMessage();

    /**
     * <code>optional string error_message = 14;</code>
     *
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString getErrorMessageBytes();

    /**
     * <code>optional uint32 ip = 15;</code>
     *
     * @return Whether the ip field is set.
     */
    boolean hasIp();

    /**
     * <code>optional uint32 ip = 15;</code>
     *
     * @return The ip.
     */
    int getIp();

    /**
     * <code>optional .GCProtoBufMsgSrc gc_msg_src = 200 [default = GCProtoBufMsgSrc_Unspecified];
     * </code>
     *
     * @return Whether the gcMsgSrc field is set.
     */
    boolean hasGcMsgSrc();

    /**
     * <code>optional .GCProtoBufMsgSrc gc_msg_src = 200 [default = GCProtoBufMsgSrc_Unspecified];
     * </code>
     *
     * @return The gcMsgSrc.
     */
    GCProtoBufMsgSrc getGcMsgSrc();

    /**
     * <code>optional uint32 gc_dir_index_source = 201;</code>
     *
     * @return Whether the gcDirIndexSource field is set.
     */
    boolean hasGcDirIndexSource();

    /**
     * <code>optional uint32 gc_dir_index_source = 201;</code>
     *
     * @return The gcDirIndexSource.
     */
    int getGcDirIndexSource();
  }

  /** Protobuf type {@code CMsgProtoBufHeader} */
  public static final class CMsgProtoBufHeader extends com.google.protobuf.GeneratedMessage
      implements
      // @@protoc_insertion_point(message_implements:CMsgProtoBufHeader)
      CMsgProtoBufHeaderOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          CMsgProtoBufHeader.class.getName());
    }

    // Use CMsgProtoBufHeader.newBuilder() to construct.
    private CMsgProtoBufHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }

    private CMsgProtoBufHeader() {
      jobIdSource_ = -1L;
      jobIdTarget_ = -1L;
      targetJobName_ = "";
      eresult_ = 2;
      errorMessage_ = "";
      gcMsgSrc_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return GameCoordinatorMessages.internal_static_CMsgProtoBufHeader_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return GameCoordinatorMessages.internal_static_CMsgProtoBufHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(CMsgProtoBufHeader.class, Builder.class);
    }

    private int bitField0_;
    public static final int CLIENT_STEAM_ID_FIELD_NUMBER = 1;
    private long clientSteamId_ = 0L;

    /**
     * <code>optional fixed64 client_steam_id = 1;</code>
     *
     * @return Whether the clientSteamId field is set.
     */
    @Override
    public boolean hasClientSteamId() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional fixed64 client_steam_id = 1;</code>
     *
     * @return The clientSteamId.
     */
    @Override
    public long getClientSteamId() {
      return clientSteamId_;
    }

    public static final int CLIENT_SESSION_ID_FIELD_NUMBER = 2;
    private int clientSessionId_ = 0;

    /**
     * <code>optional int32 client_session_id = 2;</code>
     *
     * @return Whether the clientSessionId field is set.
     */
    @Override
    public boolean hasClientSessionId() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional int32 client_session_id = 2;</code>
     *
     * @return The clientSessionId.
     */
    @Override
    public int getClientSessionId() {
      return clientSessionId_;
    }

    public static final int SOURCE_APP_ID_FIELD_NUMBER = 3;
    private int sourceAppId_ = 0;

    /**
     * <code>optional uint32 source_app_id = 3;</code>
     *
     * @return Whether the sourceAppId field is set.
     */
    @Override
    public boolean hasSourceAppId() {
      return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>optional uint32 source_app_id = 3;</code>
     *
     * @return The sourceAppId.
     */
    @Override
    public int getSourceAppId() {
      return sourceAppId_;
    }

    public static final int JOB_ID_SOURCE_FIELD_NUMBER = 10;
    private long jobIdSource_ = -1L;

    /**
     * <code>optional fixed64 job_id_source = 10 [default = 18446744073709551615];</code>
     *
     * @return Whether the jobIdSource field is set.
     */
    @Override
    public boolean hasJobIdSource() {
      return ((bitField0_ & 0x00000008) != 0);
    }

    /**
     * <code>optional fixed64 job_id_source = 10 [default = 18446744073709551615];</code>
     *
     * @return The jobIdSource.
     */
    @Override
    public long getJobIdSource() {
      return jobIdSource_;
    }

    public static final int JOB_ID_TARGET_FIELD_NUMBER = 11;
    private long jobIdTarget_ = -1L;

    /**
     * <code>optional fixed64 job_id_target = 11 [default = 18446744073709551615];</code>
     *
     * @return Whether the jobIdTarget field is set.
     */
    @Override
    public boolean hasJobIdTarget() {
      return ((bitField0_ & 0x00000010) != 0);
    }

    /**
     * <code>optional fixed64 job_id_target = 11 [default = 18446744073709551615];</code>
     *
     * @return The jobIdTarget.
     */
    @Override
    public long getJobIdTarget() {
      return jobIdTarget_;
    }

    public static final int TARGET_JOB_NAME_FIELD_NUMBER = 12;

    @SuppressWarnings("serial")
    private volatile Object targetJobName_ = "";

    /**
     * <code>optional string target_job_name = 12;</code>
     *
     * @return Whether the targetJobName field is set.
     */
    @Override
    public boolean hasTargetJobName() {
      return ((bitField0_ & 0x00000020) != 0);
    }

    /**
     * <code>optional string target_job_name = 12;</code>
     *
     * @return The targetJobName.
     */
    @Override
    public String getTargetJobName() {
      Object ref = targetJobName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetJobName_ = s;
        }
        return s;
      }
    }

    /**
     * <code>optional string target_job_name = 12;</code>
     *
     * @return The bytes for targetJobName.
     */
    @Override
    public com.google.protobuf.ByteString getTargetJobNameBytes() {
      Object ref = targetJobName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        targetJobName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERESULT_FIELD_NUMBER = 13;
    private int eresult_ = 2;

    /**
     * <code>optional int32 eresult = 13 [default = 2];</code>
     *
     * @return Whether the eresult field is set.
     */
    @Override
    public boolean hasEresult() {
      return ((bitField0_ & 0x00000040) != 0);
    }

    /**
     * <code>optional int32 eresult = 13 [default = 2];</code>
     *
     * @return The eresult.
     */
    @Override
    public int getEresult() {
      return eresult_;
    }

    public static final int ERROR_MESSAGE_FIELD_NUMBER = 14;

    @SuppressWarnings("serial")
    private volatile Object errorMessage_ = "";

    /**
     * <code>optional string error_message = 14;</code>
     *
     * @return Whether the errorMessage field is set.
     */
    @Override
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000080) != 0);
    }

    /**
     * <code>optional string error_message = 14;</code>
     *
     * @return The errorMessage.
     */
    @Override
    public String getErrorMessage() {
      Object ref = errorMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }

    /**
     * <code>optional string error_message = 14;</code>
     *
     * @return The bytes for errorMessage.
     */
    @Override
    public com.google.protobuf.ByteString getErrorMessageBytes() {
      Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 15;
    private int ip_ = 0;

    /**
     * <code>optional uint32 ip = 15;</code>
     *
     * @return Whether the ip field is set.
     */
    @Override
    public boolean hasIp() {
      return ((bitField0_ & 0x00000100) != 0);
    }

    /**
     * <code>optional uint32 ip = 15;</code>
     *
     * @return The ip.
     */
    @Override
    public int getIp() {
      return ip_;
    }

    public static final int GC_MSG_SRC_FIELD_NUMBER = 200;
    private int gcMsgSrc_ = 0;

    /**
     * <code>optional .GCProtoBufMsgSrc gc_msg_src = 200 [default = GCProtoBufMsgSrc_Unspecified];
     * </code>
     *
     * @return Whether the gcMsgSrc field is set.
     */
    @Override
    public boolean hasGcMsgSrc() {
      return ((bitField0_ & 0x00000200) != 0);
    }

    /**
     * <code>optional .GCProtoBufMsgSrc gc_msg_src = 200 [default = GCProtoBufMsgSrc_Unspecified];
     * </code>
     *
     * @return The gcMsgSrc.
     */
    @Override
    public GCProtoBufMsgSrc getGcMsgSrc() {
      GCProtoBufMsgSrc result = GCProtoBufMsgSrc.forNumber(gcMsgSrc_);
      return result == null ? GCProtoBufMsgSrc.GCProtoBufMsgSrc_Unspecified : result;
    }

    public static final int GC_DIR_INDEX_SOURCE_FIELD_NUMBER = 201;
    private int gcDirIndexSource_ = 0;

    /**
     * <code>optional uint32 gc_dir_index_source = 201;</code>
     *
     * @return Whether the gcDirIndexSource field is set.
     */
    @Override
    public boolean hasGcDirIndexSource() {
      return ((bitField0_ & 0x00000400) != 0);
    }

    /**
     * <code>optional uint32 gc_dir_index_source = 201;</code>
     *
     * @return The gcDirIndexSource.
     */
    @Override
    public int getGcDirIndexSource() {
      return gcDirIndexSource_;
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeFixed64(1, clientSteamId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, clientSessionId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, sourceAppId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeFixed64(10, jobIdSource_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeFixed64(11, jobIdTarget_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 12, targetJobName_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(13, eresult_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 14, errorMessage_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeUInt32(15, ip_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeEnum(200, gcMsgSrc_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeUInt32(201, gcDirIndexSource_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream.computeFixed64Size(1, clientSteamId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, clientSessionId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(3, sourceAppId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream.computeFixed64Size(10, jobIdSource_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream.computeFixed64Size(11, jobIdTarget_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(12, targetJobName_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(13, eresult_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(14, errorMessage_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(15, ip_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream.computeEnumSize(200, gcMsgSrc_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(201, gcDirIndexSource_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof CMsgProtoBufHeader)) {
        return super.equals(obj);
      }
      CMsgProtoBufHeader other = (CMsgProtoBufHeader) obj;

      if (hasClientSteamId() != other.hasClientSteamId()) return false;
      if (hasClientSteamId()) {
        if (getClientSteamId() != other.getClientSteamId()) return false;
      }
      if (hasClientSessionId() != other.hasClientSessionId()) return false;
      if (hasClientSessionId()) {
        if (getClientSessionId() != other.getClientSessionId()) return false;
      }
      if (hasSourceAppId() != other.hasSourceAppId()) return false;
      if (hasSourceAppId()) {
        if (getSourceAppId() != other.getSourceAppId()) return false;
      }
      if (hasJobIdSource() != other.hasJobIdSource()) return false;
      if (hasJobIdSource()) {
        if (getJobIdSource() != other.getJobIdSource()) return false;
      }
      if (hasJobIdTarget() != other.hasJobIdTarget()) return false;
      if (hasJobIdTarget()) {
        if (getJobIdTarget() != other.getJobIdTarget()) return false;
      }
      if (hasTargetJobName() != other.hasTargetJobName()) return false;
      if (hasTargetJobName()) {
        if (!getTargetJobName().equals(other.getTargetJobName())) return false;
      }
      if (hasEresult() != other.hasEresult()) return false;
      if (hasEresult()) {
        if (getEresult() != other.getEresult()) return false;
      }
      if (hasErrorMessage() != other.hasErrorMessage()) return false;
      if (hasErrorMessage()) {
        if (!getErrorMessage().equals(other.getErrorMessage())) return false;
      }
      if (hasIp() != other.hasIp()) return false;
      if (hasIp()) {
        if (getIp() != other.getIp()) return false;
      }
      if (hasGcMsgSrc() != other.hasGcMsgSrc()) return false;
      if (hasGcMsgSrc()) {
        if (gcMsgSrc_ != other.gcMsgSrc_) return false;
      }
      if (hasGcDirIndexSource() != other.hasGcDirIndexSource()) return false;
      if (hasGcDirIndexSource()) {
        if (getGcDirIndexSource() != other.getGcDirIndexSource()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasClientSteamId()) {
        hash = (37 * hash) + CLIENT_STEAM_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getClientSteamId());
      }
      if (hasClientSessionId()) {
        hash = (37 * hash) + CLIENT_SESSION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getClientSessionId();
      }
      if (hasSourceAppId()) {
        hash = (37 * hash) + SOURCE_APP_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSourceAppId();
      }
      if (hasJobIdSource()) {
        hash = (37 * hash) + JOB_ID_SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getJobIdSource());
      }
      if (hasJobIdTarget()) {
        hash = (37 * hash) + JOB_ID_TARGET_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getJobIdTarget());
      }
      if (hasTargetJobName()) {
        hash = (37 * hash) + TARGET_JOB_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getTargetJobName().hashCode();
      }
      if (hasEresult()) {
        hash = (37 * hash) + ERESULT_FIELD_NUMBER;
        hash = (53 * hash) + getEresult();
      }
      if (hasErrorMessage()) {
        hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp();
      }
      if (hasGcMsgSrc()) {
        hash = (37 * hash) + GC_MSG_SRC_FIELD_NUMBER;
        hash = (53 * hash) + gcMsgSrc_;
      }
      if (hasGcDirIndexSource()) {
        hash = (37 * hash) + GC_DIR_INDEX_SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getGcDirIndexSource();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CMsgProtoBufHeader parseFrom(java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static CMsgProtoBufHeader parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static CMsgProtoBufHeader parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static CMsgProtoBufHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static CMsgProtoBufHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static CMsgProtoBufHeader parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static CMsgProtoBufHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static CMsgProtoBufHeader parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static CMsgProtoBufHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static CMsgProtoBufHeader parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static CMsgProtoBufHeader parseFrom(com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static CMsgProtoBufHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(CMsgProtoBufHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /** Protobuf type {@code CMsgProtoBufHeader} */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:CMsgProtoBufHeader)
        CMsgProtoBufHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return GameCoordinatorMessages.internal_static_CMsgProtoBufHeader_descriptor;
      }

      @Override
      protected FieldAccessorTable internalGetFieldAccessorTable() {
        return GameCoordinatorMessages.internal_static_CMsgProtoBufHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(CMsgProtoBufHeader.class, Builder.class);
      }

      // Construct using GameCoordinatorMessages.CMsgProtoBufHeader.newBuilder()
      private Builder() {}

      private Builder(BuilderParent parent) {
        super(parent);
      }

      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        clientSteamId_ = 0L;
        clientSessionId_ = 0;
        sourceAppId_ = 0;
        jobIdSource_ = -1L;
        jobIdTarget_ = -1L;
        targetJobName_ = "";
        eresult_ = 2;
        errorMessage_ = "";
        ip_ = 0;
        gcMsgSrc_ = 0;
        gcDirIndexSource_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return GameCoordinatorMessages.internal_static_CMsgProtoBufHeader_descriptor;
      }

      @Override
      public CMsgProtoBufHeader getDefaultInstanceForType() {
        return CMsgProtoBufHeader.getDefaultInstance();
      }

      @Override
      public CMsgProtoBufHeader build() {
        CMsgProtoBufHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CMsgProtoBufHeader buildPartial() {
        CMsgProtoBufHeader result = new CMsgProtoBufHeader(this);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        onBuilt();
        return result;
      }

      private void buildPartial0(CMsgProtoBufHeader result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.clientSteamId_ = clientSteamId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.clientSessionId_ = clientSessionId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sourceAppId_ = sourceAppId_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.jobIdSource_ = jobIdSource_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.jobIdTarget_ = jobIdTarget_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.targetJobName_ = targetJobName_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.eresult_ = eresult_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.errorMessage_ = errorMessage_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.ip_ = ip_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.gcMsgSrc_ = gcMsgSrc_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.gcDirIndexSource_ = gcDirIndexSource_;
          to_bitField0_ |= 0x00000400;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CMsgProtoBufHeader) {
          return mergeFrom((CMsgProtoBufHeader) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CMsgProtoBufHeader other) {
        if (other == CMsgProtoBufHeader.getDefaultInstance()) return this;
        if (other.hasClientSteamId()) {
          setClientSteamId(other.getClientSteamId());
        }
        if (other.hasClientSessionId()) {
          setClientSessionId(other.getClientSessionId());
        }
        if (other.hasSourceAppId()) {
          setSourceAppId(other.getSourceAppId());
        }
        if (other.hasJobIdSource()) {
          setJobIdSource(other.getJobIdSource());
        }
        if (other.hasJobIdTarget()) {
          setJobIdTarget(other.getJobIdTarget());
        }
        if (other.hasTargetJobName()) {
          targetJobName_ = other.targetJobName_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasEresult()) {
          setEresult(other.getEresult());
        }
        if (other.hasErrorMessage()) {
          errorMessage_ = other.errorMessage_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasGcMsgSrc()) {
          setGcMsgSrc(other.getGcMsgSrc());
        }
        if (other.hasGcDirIndexSource()) {
          setGcDirIndexSource(other.getGcDirIndexSource());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9:
                {
                  clientSteamId_ = input.readFixed64();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 9
              case 16:
                {
                  clientSessionId_ = input.readInt32();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 16
              case 24:
                {
                  sourceAppId_ = input.readUInt32();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 24
              case 81:
                {
                  jobIdSource_ = input.readFixed64();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 81
              case 89:
                {
                  jobIdTarget_ = input.readFixed64();
                  bitField0_ |= 0x00000010;
                  break;
                } // case 89
              case 98:
                {
                  targetJobName_ = input.readBytes();
                  bitField0_ |= 0x00000020;
                  break;
                } // case 98
              case 104:
                {
                  eresult_ = input.readInt32();
                  bitField0_ |= 0x00000040;
                  break;
                } // case 104
              case 114:
                {
                  errorMessage_ = input.readBytes();
                  bitField0_ |= 0x00000080;
                  break;
                } // case 114
              case 120:
                {
                  ip_ = input.readUInt32();
                  bitField0_ |= 0x00000100;
                  break;
                } // case 120
              case 1600:
                {
                  int tmpRaw = input.readEnum();
                  GCProtoBufMsgSrc tmpValue = GCProtoBufMsgSrc.forNumber(tmpRaw);
                  if (tmpValue == null) {
                    mergeUnknownVarintField(200, tmpRaw);
                  } else {
                    gcMsgSrc_ = tmpRaw;
                    bitField0_ |= 0x00000200;
                  }
                  break;
                } // case 1600
              case 1608:
                {
                  gcDirIndexSource_ = input.readUInt32();
                  bitField0_ |= 0x00000400;
                  break;
                } // case 1608
              default:
                {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int bitField0_;

      private long clientSteamId_;

      /**
       * <code>optional fixed64 client_steam_id = 1;</code>
       *
       * @return Whether the clientSteamId field is set.
       */
      @Override
      public boolean hasClientSteamId() {
        return ((bitField0_ & 0x00000001) != 0);
      }

      /**
       * <code>optional fixed64 client_steam_id = 1;</code>
       *
       * @return The clientSteamId.
       */
      @Override
      public long getClientSteamId() {
        return clientSteamId_;
      }

      /**
       * <code>optional fixed64 client_steam_id = 1;</code>
       *
       * @param value The clientSteamId to set.
       * @return This builder for chaining.
       */
      public Builder setClientSteamId(long value) {

        clientSteamId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <code>optional fixed64 client_steam_id = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearClientSteamId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientSteamId_ = 0L;
        onChanged();
        return this;
      }

      private int clientSessionId_;

      /**
       * <code>optional int32 client_session_id = 2;</code>
       *
       * @return Whether the clientSessionId field is set.
       */
      @Override
      public boolean hasClientSessionId() {
        return ((bitField0_ & 0x00000002) != 0);
      }

      /**
       * <code>optional int32 client_session_id = 2;</code>
       *
       * @return The clientSessionId.
       */
      @Override
      public int getClientSessionId() {
        return clientSessionId_;
      }

      /**
       * <code>optional int32 client_session_id = 2;</code>
       *
       * @param value The clientSessionId to set.
       * @return This builder for chaining.
       */
      public Builder setClientSessionId(int value) {

        clientSessionId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 client_session_id = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearClientSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientSessionId_ = 0;
        onChanged();
        return this;
      }

      private int sourceAppId_;

      /**
       * <code>optional uint32 source_app_id = 3;</code>
       *
       * @return Whether the sourceAppId field is set.
       */
      @Override
      public boolean hasSourceAppId() {
        return ((bitField0_ & 0x00000004) != 0);
      }

      /**
       * <code>optional uint32 source_app_id = 3;</code>
       *
       * @return The sourceAppId.
       */
      @Override
      public int getSourceAppId() {
        return sourceAppId_;
      }

      /**
       * <code>optional uint32 source_app_id = 3;</code>
       *
       * @param value The sourceAppId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceAppId(int value) {

        sourceAppId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint32 source_app_id = 3;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearSourceAppId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sourceAppId_ = 0;
        onChanged();
        return this;
      }

      private long jobIdSource_ = -1L;

      /**
       * <code>optional fixed64 job_id_source = 10 [default = 18446744073709551615];</code>
       *
       * @return Whether the jobIdSource field is set.
       */
      @Override
      public boolean hasJobIdSource() {
        return ((bitField0_ & 0x00000008) != 0);
      }

      /**
       * <code>optional fixed64 job_id_source = 10 [default = 18446744073709551615];</code>
       *
       * @return The jobIdSource.
       */
      @Override
      public long getJobIdSource() {
        return jobIdSource_;
      }

      /**
       * <code>optional fixed64 job_id_source = 10 [default = 18446744073709551615];</code>
       *
       * @param value The jobIdSource to set.
       * @return This builder for chaining.
       */
      public Builder setJobIdSource(long value) {

        jobIdSource_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      /**
       * <code>optional fixed64 job_id_source = 10 [default = 18446744073709551615];</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearJobIdSource() {
        bitField0_ = (bitField0_ & ~0x00000008);
        jobIdSource_ = -1L;
        onChanged();
        return this;
      }

      private long jobIdTarget_ = -1L;

      /**
       * <code>optional fixed64 job_id_target = 11 [default = 18446744073709551615];</code>
       *
       * @return Whether the jobIdTarget field is set.
       */
      @Override
      public boolean hasJobIdTarget() {
        return ((bitField0_ & 0x00000010) != 0);
      }

      /**
       * <code>optional fixed64 job_id_target = 11 [default = 18446744073709551615];</code>
       *
       * @return The jobIdTarget.
       */
      @Override
      public long getJobIdTarget() {
        return jobIdTarget_;
      }

      /**
       * <code>optional fixed64 job_id_target = 11 [default = 18446744073709551615];</code>
       *
       * @param value The jobIdTarget to set.
       * @return This builder for chaining.
       */
      public Builder setJobIdTarget(long value) {

        jobIdTarget_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      /**
       * <code>optional fixed64 job_id_target = 11 [default = 18446744073709551615];</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearJobIdTarget() {
        bitField0_ = (bitField0_ & ~0x00000010);
        jobIdTarget_ = -1L;
        onChanged();
        return this;
      }

      private Object targetJobName_ = "";

      /**
       * <code>optional string target_job_name = 12;</code>
       *
       * @return Whether the targetJobName field is set.
       */
      public boolean hasTargetJobName() {
        return ((bitField0_ & 0x00000020) != 0);
      }

      /**
       * <code>optional string target_job_name = 12;</code>
       *
       * @return The targetJobName.
       */
      public String getTargetJobName() {
        Object ref = targetJobName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            targetJobName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>optional string target_job_name = 12;</code>
       *
       * @return The bytes for targetJobName.
       */
      public com.google.protobuf.ByteString getTargetJobNameBytes() {
        Object ref = targetJobName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          targetJobName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string target_job_name = 12;</code>
       *
       * @param value The targetJobName to set.
       * @return This builder for chaining.
       */
      public Builder setTargetJobName(String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        targetJobName_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      /**
       * <code>optional string target_job_name = 12;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearTargetJobName() {
        targetJobName_ = getDefaultInstance().getTargetJobName();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      /**
       * <code>optional string target_job_name = 12;</code>
       *
       * @param value The bytes for targetJobName to set.
       * @return This builder for chaining.
       */
      public Builder setTargetJobNameBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        targetJobName_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private int eresult_ = 2;

      /**
       * <code>optional int32 eresult = 13 [default = 2];</code>
       *
       * @return Whether the eresult field is set.
       */
      @Override
      public boolean hasEresult() {
        return ((bitField0_ & 0x00000040) != 0);
      }

      /**
       * <code>optional int32 eresult = 13 [default = 2];</code>
       *
       * @return The eresult.
       */
      @Override
      public int getEresult() {
        return eresult_;
      }

      /**
       * <code>optional int32 eresult = 13 [default = 2];</code>
       *
       * @param value The eresult to set.
       * @return This builder for chaining.
       */
      public Builder setEresult(int value) {

        eresult_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 eresult = 13 [default = 2];</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearEresult() {
        bitField0_ = (bitField0_ & ~0x00000040);
        eresult_ = 2;
        onChanged();
        return this;
      }

      private Object errorMessage_ = "";

      /**
       * <code>optional string error_message = 14;</code>
       *
       * @return Whether the errorMessage field is set.
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000080) != 0);
      }

      /**
       * <code>optional string error_message = 14;</code>
       *
       * @return The errorMessage.
       */
      public String getErrorMessage() {
        Object ref = errorMessage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>optional string error_message = 14;</code>
       *
       * @return The bytes for errorMessage.
       */
      public com.google.protobuf.ByteString getErrorMessageBytes() {
        Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string error_message = 14;</code>
       *
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        errorMessage_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      /**
       * <code>optional string error_message = 14;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        errorMessage_ = getDefaultInstance().getErrorMessage();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }

      /**
       * <code>optional string error_message = 14;</code>
       *
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        errorMessage_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private int ip_;

      /**
       * <code>optional uint32 ip = 15;</code>
       *
       * @return Whether the ip field is set.
       */
      @Override
      public boolean hasIp() {
        return ((bitField0_ & 0x00000100) != 0);
      }

      /**
       * <code>optional uint32 ip = 15;</code>
       *
       * @return The ip.
       */
      @Override
      public int getIp() {
        return ip_;
      }

      /**
       * <code>optional uint32 ip = 15;</code>
       *
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(int value) {

        ip_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint32 ip = 15;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000100);
        ip_ = 0;
        onChanged();
        return this;
      }

      private int gcMsgSrc_ = 0;

      /**
       * <code>optional .GCProtoBufMsgSrc gc_msg_src = 200 [default = GCProtoBufMsgSrc_Unspecified];
       * </code>
       *
       * @return Whether the gcMsgSrc field is set.
       */
      @Override
      public boolean hasGcMsgSrc() {
        return ((bitField0_ & 0x00000200) != 0);
      }

      /**
       * <code>optional .GCProtoBufMsgSrc gc_msg_src = 200 [default = GCProtoBufMsgSrc_Unspecified];
       * </code>
       *
       * @return The gcMsgSrc.
       */
      @Override
      public GCProtoBufMsgSrc getGcMsgSrc() {
        GCProtoBufMsgSrc result = GCProtoBufMsgSrc.forNumber(gcMsgSrc_);
        return result == null ? GCProtoBufMsgSrc.GCProtoBufMsgSrc_Unspecified : result;
      }

      /**
       * <code>optional .GCProtoBufMsgSrc gc_msg_src = 200 [default = GCProtoBufMsgSrc_Unspecified];
       * </code>
       *
       * @param value The gcMsgSrc to set.
       * @return This builder for chaining.
       */
      public Builder setGcMsgSrc(GCProtoBufMsgSrc value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000200;
        gcMsgSrc_ = value.getNumber();
        onChanged();
        return this;
      }

      /**
       * <code>optional .GCProtoBufMsgSrc gc_msg_src = 200 [default = GCProtoBufMsgSrc_Unspecified];
       * </code>
       *
       * @return This builder for chaining.
       */
      public Builder clearGcMsgSrc() {
        bitField0_ = (bitField0_ & ~0x00000200);
        gcMsgSrc_ = 0;
        onChanged();
        return this;
      }

      private int gcDirIndexSource_;

      /**
       * <code>optional uint32 gc_dir_index_source = 201;</code>
       *
       * @return Whether the gcDirIndexSource field is set.
       */
      @Override
      public boolean hasGcDirIndexSource() {
        return ((bitField0_ & 0x00000400) != 0);
      }

      /**
       * <code>optional uint32 gc_dir_index_source = 201;</code>
       *
       * @return The gcDirIndexSource.
       */
      @Override
      public int getGcDirIndexSource() {
        return gcDirIndexSource_;
      }

      /**
       * <code>optional uint32 gc_dir_index_source = 201;</code>
       *
       * @param value The gcDirIndexSource to set.
       * @return This builder for chaining.
       */
      public Builder setGcDirIndexSource(int value) {

        gcDirIndexSource_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint32 gc_dir_index_source = 201;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearGcDirIndexSource() {
        bitField0_ = (bitField0_ & ~0x00000400);
        gcDirIndexSource_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CMsgProtoBufHeader)
    }

    // @@protoc_insertion_point(class_scope:CMsgProtoBufHeader)
    private static final CMsgProtoBufHeader DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new CMsgProtoBufHeader();
    }

    public static CMsgProtoBufHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CMsgProtoBufHeader> PARSER =
        new com.google.protobuf.AbstractParser<CMsgProtoBufHeader>() {
          @Override
          public CMsgProtoBufHeader parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
              builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
              throw e.asInvalidProtocolBufferException()
                  .setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
              throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
          }
        };

    public static com.google.protobuf.Parser<CMsgProtoBufHeader> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CMsgProtoBufHeader> getParserForType() {
      return PARSER;
    }

    @Override
    public CMsgProtoBufHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  public static final int MSGPOOL_SOFT_LIMIT_FIELD_NUMBER = 60000;

  /** <code>extend .google.protobuf.MessageOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.MessageOptions, Integer>
      msgpoolSoftLimit =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(Integer.class, null);

  public static final int MSGPOOL_HARD_LIMIT_FIELD_NUMBER = 60001;

  /** <code>extend .google.protobuf.MessageOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.MessageOptions, Integer>
      msgpoolHardLimit =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(Integer.class, null);

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_CMsgProtoBufHeader_descriptor;
  private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CMsgProtoBufHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    String[] descriptorData = {
      "\n\037game_coordinator_messages.proto\032 googl"
          + "e/protobuf/descriptor.proto\"\371\002\n\022CMsgProt"
          + "oBufHeader\022\027\n\017client_steam_id\030\001 \001(\006\022\031\n\021c"
          + "lient_session_id\030\002 \001(\005\022\025\n\rsource_app_id\030"
          + "\003 \001(\r\022+\n\rjob_id_source\030\n \001(\006:\0241844674407"
          + "3709551615\022+\n\rjob_id_target\030\013 \001(\006:\02418446"
          + "744073709551615\022\027\n\017target_job_name\030\014 \001(\t"
          + "\022\022\n\007eresult\030\r \001(\005:\0012\022\025\n\rerror_message\030\016 "
          + "\001(\t\022\n\n\002ip\030\017 \001(\r\022D\n\ngc_msg_src\030\310\001 \001(\0162\021.G"
          + "CProtoBufMsgSrc:\034GCProtoBufMsgSrc_Unspec"
          + "ified\022\034\n\023gc_dir_index_source\030\311\001 \001(\r:\n\200\246\035"
          + "\200\002\210\246\035\200\010*\266\001\n\020GCProtoBufMsgSrc\022 \n\034GCProtoB"
          + "ufMsgSrc_Unspecified\020\000\022\037\n\033GCProtoBufMsgS"
          + "rc_FromSystem\020\001\022 \n\034GCProtoBufMsgSrc_From"
          + "SteamID\020\002\022\033\n\027GCProtoBufMsgSrc_FromGC\020\003\022 "
          + "\n\034GCProtoBufMsgSrc_ReplySystem\020\004:A\n\022msgp"
          + "ool_soft_limit\022\037.google.protobuf.Message"
          + "Options\030\340\324\003 \001(\005:\00232:B\n\022msgpool_hard_limi"
          + "t\022\037.google.protobuf.MessageOptions\030\341\324\003 \001"
          + "(\005:\003384"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.DescriptorProtos.getDescriptor(),
            });
    internal_static_CMsgProtoBufHeader_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_CMsgProtoBufHeader_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_CMsgProtoBufHeader_descriptor,
            new String[] {
              "ClientSteamId",
              "ClientSessionId",
              "SourceAppId",
              "JobIdSource",
              "JobIdTarget",
              "TargetJobName",
              "Eresult",
              "ErrorMessage",
              "Ip",
              "GcMsgSrc",
              "GcDirIndexSource",
            });
    msgpoolSoftLimit.internalInit(descriptor.getExtensions().get(0));
    msgpoolHardLimit.internalInit(descriptor.getExtensions().get(1));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(GameCoordinatorMessages.msgpoolHardLimit);
    registry.add(GameCoordinatorMessages.msgpoolSoftLimit);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
