// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_unified_base.steamclient.proto
// Protobuf Java Version: 4.26.1
package com.javasteam.protobufs;

public final class SteammessagesUnifiedBaseSteamclient {
  private SteammessagesUnifiedBaseSteamclient() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        SteammessagesUnifiedBaseSteamclient.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(SteammessagesUnifiedBaseSteamclient.messageDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.forceEmitMessage);
    registry.add(SteammessagesUnifiedBaseSteamclient.description);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceExecutionSite);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceType);
    registry.add(SteammessagesUnifiedBaseSteamclient.forceEmitService);
    registry.add(SteammessagesUnifiedBaseSteamclient.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.enumDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.enumValueDescription);
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  /** Protobuf enum {@code EProtoExecutionSite} */
  public enum EProtoExecutionSite implements com.google.protobuf.ProtocolMessageEnum {
    /** <code>k_EProtoExecutionSiteUnknown = 0;</code> */
    k_EProtoExecutionSiteUnknown(0),
    /** <code>k_EProtoExecutionSiteSteamClient = 2;</code> */
    k_EProtoExecutionSiteSteamClient(2),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          EProtoExecutionSite.class.getName());
    }

    /** <code>k_EProtoExecutionSiteUnknown = 0;</code> */
    public static final int k_EProtoExecutionSiteUnknown_VALUE = 0;

    /** <code>k_EProtoExecutionSiteSteamClient = 2;</code> */
    public static final int k_EProtoExecutionSiteSteamClient_VALUE = 2;

    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static EProtoExecutionSite valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EProtoExecutionSite forNumber(int value) {
      switch (value) {
        case 0:
          return k_EProtoExecutionSiteUnknown;
        case 2:
          return k_EProtoExecutionSiteSteamClient;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EProtoExecutionSite>
        internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<EProtoExecutionSite>
        internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EProtoExecutionSite>() {
              public EProtoExecutionSite findValueByNumber(int number) {
                return EProtoExecutionSite.forNumber(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
      return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
      return SteammessagesUnifiedBaseSteamclient.getDescriptor().getEnumTypes().get(0);
    }

    private static final EProtoExecutionSite[] VALUES = values();

    public static EProtoExecutionSite valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EProtoExecutionSite(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EProtoExecutionSite)
  }

  /** Protobuf enum {@code EProtoServiceType} */
  public enum EProtoServiceType implements com.google.protobuf.ProtocolMessageEnum {
    /** <code>k_EProtoServiceTypeSteamMessages = 0;</code> */
    k_EProtoServiceTypeSteamMessages(0),
    /** <code>k_EProtoServiceTypeVRGamepadUIMessages = 1;</code> */
    k_EProtoServiceTypeVRGamepadUIMessages(1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          EProtoServiceType.class.getName());
    }

    /** <code>k_EProtoServiceTypeSteamMessages = 0;</code> */
    public static final int k_EProtoServiceTypeSteamMessages_VALUE = 0;

    /** <code>k_EProtoServiceTypeVRGamepadUIMessages = 1;</code> */
    public static final int k_EProtoServiceTypeVRGamepadUIMessages_VALUE = 1;

    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static EProtoServiceType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EProtoServiceType forNumber(int value) {
      switch (value) {
        case 0:
          return k_EProtoServiceTypeSteamMessages;
        case 1:
          return k_EProtoServiceTypeVRGamepadUIMessages;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EProtoServiceType>
        internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<EProtoServiceType>
        internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EProtoServiceType>() {
              public EProtoServiceType findValueByNumber(int number) {
                return EProtoServiceType.forNumber(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
      return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
      return SteammessagesUnifiedBaseSteamclient.getDescriptor().getEnumTypes().get(1);
    }

    private static final EProtoServiceType[] VALUES = values();

    public static EProtoServiceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EProtoServiceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EProtoServiceType)
  }

  public interface NoResponseOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:NoResponse)
      com.google.protobuf.MessageOrBuilder {}

  /** Protobuf type {@code NoResponse} */
  public static final class NoResponse extends com.google.protobuf.GeneratedMessage
      implements
      // @@protoc_insertion_point(message_implements:NoResponse)
      NoResponseOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          NoResponse.class.getName());
    }

    // Use NoResponse.newBuilder() to construct.
    private NoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }

    private NoResponse() {}

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return SteammessagesUnifiedBaseSteamclient.internal_static_NoResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return SteammessagesUnifiedBaseSteamclient.internal_static_NoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(NoResponse.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof NoResponse)) {
        return super.equals(obj);
      }
      NoResponse other = (NoResponse) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NoResponse parseFrom(java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static NoResponse parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NoResponse parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static NoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static NoResponse parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NoResponse parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static NoResponse parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static NoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static NoResponse parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static NoResponse parseFrom(com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static NoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(NoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /** Protobuf type {@code NoResponse} */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:NoResponse)
        NoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return SteammessagesUnifiedBaseSteamclient.internal_static_NoResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable internalGetFieldAccessorTable() {
        return SteammessagesUnifiedBaseSteamclient.internal_static_NoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(NoResponse.class, Builder.class);
      }

      // Construct using SteammessagesUnifiedBaseSteamclient.NoResponse.newBuilder()
      private Builder() {}

      private Builder(BuilderParent parent) {
        super(parent);
      }

      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return SteammessagesUnifiedBaseSteamclient.internal_static_NoResponse_descriptor;
      }

      @Override
      public NoResponse getDefaultInstanceForType() {
        return NoResponse.getDefaultInstance();
      }

      @Override
      public NoResponse build() {
        NoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NoResponse buildPartial() {
        NoResponse result = new NoResponse(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NoResponse) {
          return mergeFrom((NoResponse) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NoResponse other) {
        if (other == NoResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default:
                {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NoResponse)
    }

    // @@protoc_insertion_point(class_scope:NoResponse)
    private static final NoResponse DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new NoResponse();
    }

    public static NoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NoResponse> PARSER =
        new com.google.protobuf.AbstractParser<NoResponse>() {
          @Override
          public NoResponse parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
              builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
              throw e.asInvalidProtocolBufferException()
                  .setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
              throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
          }
        };

    public static com.google.protobuf.Parser<NoResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NoResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public NoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  public static final int MESSAGE_DESCRIPTION_FIELD_NUMBER = 51000;

  /** <code>extend .google.protobuf.MessageOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.MessageOptions, String>
      messageDescription =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(String.class, null);

  public static final int FORCE_EMIT_MESSAGE_FIELD_NUMBER = 50026;

  /** <code>extend .google.protobuf.MessageOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.MessageOptions, Boolean>
      forceEmitMessage =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(Boolean.class, null);

  public static final int DESCRIPTION_FIELD_NUMBER = 50000;

  /** <code>extend .google.protobuf.FieldOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.FieldOptions, String>
      description =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(String.class, null);

  public static final int SERVICE_DESCRIPTION_FIELD_NUMBER = 50000;

  /** <code>extend .google.protobuf.ServiceOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.ServiceOptions, String>
      serviceDescription =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(String.class, null);

  public static final int SERVICE_EXECUTION_SITE_FIELD_NUMBER = 50008;

  /** <code>extend .google.protobuf.ServiceOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.ServiceOptions, EProtoExecutionSite>
      serviceExecutionSite =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(
              EProtoExecutionSite.class, null);

  public static final int SERVICE_TYPE_FIELD_NUMBER = 50025;

  /** <code>extend .google.protobuf.ServiceOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.ServiceOptions, EProtoServiceType>
      serviceType =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(
              EProtoServiceType.class, null);

  public static final int FORCE_EMIT_SERVICE_FIELD_NUMBER = 50026;

  /** <code>extend .google.protobuf.ServiceOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.ServiceOptions, Boolean>
      forceEmitService =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(Boolean.class, null);

  public static final int METHOD_DESCRIPTION_FIELD_NUMBER = 50000;

  /** <code>extend .google.protobuf.MethodOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.MethodOptions, String>
      methodDescription =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(String.class, null);

  public static final int ENUM_DESCRIPTION_FIELD_NUMBER = 50000;

  /** <code>extend .google.protobuf.EnumOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.EnumOptions, String>
      enumDescription =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(String.class, null);

  public static final int ENUM_VALUE_DESCRIPTION_FIELD_NUMBER = 50000;

  /** <code>extend .google.protobuf.EnumValueOptions { ... }</code> */
  public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.EnumValueOptions, String>
      enumValueDescription =
          com.google.protobuf.GeneratedMessage.newFileScopedGeneratedExtension(String.class, null);

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_NoResponse_descriptor;
  private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    String[] descriptorData = {
      "\n,steammessages_unified_base.steamclient"
          + ".proto\032 google/protobuf/descriptor.proto"
          + "\"\014\n\nNoResponse*]\n\023EProtoExecutionSite\022 \n"
          + "\034k_EProtoExecutionSiteUnknown\020\000\022$\n k_EPr"
          + "otoExecutionSiteSteamClient\020\002*e\n\021EProtoS"
          + "erviceType\022$\n k_EProtoServiceTypeSteamMe"
          + "ssages\020\000\022*\n&k_EProtoServiceTypeVRGamepad"
          + "UIMessages\020\001:>\n\023message_description\022\037.go"
          + "ogle.protobuf.MessageOptions\030\270\216\003 \001(\t:D\n\022"
          + "force_emit_message\022\037.google.protobuf.Mes"
          + "sageOptions\030\352\206\003 \001(\010:\005false:4\n\013descriptio"
          + "n\022\035.google.protobuf.FieldOptions\030\320\206\003 \001(\t"
          + ":>\n\023service_description\022\037.google.protobu"
          + "f.ServiceOptions\030\320\206\003 \001(\t:u\n\026service_exec"
          + "ution_site\022\037.google.protobuf.ServiceOpti"
          + "ons\030\330\206\003 \001(\0162\024.EProtoExecutionSite:\034k_EPr"
          + "otoExecutionSiteUnknown:m\n\014service_type\022"
          + "\037.google.protobuf.ServiceOptions\030\351\206\003 \001(\016"
          + "2\022.EProtoServiceType: k_EProtoServiceTyp"
          + "eSteamMessages:D\n\022force_emit_service\022\037.g"
          + "oogle.protobuf.ServiceOptions\030\352\206\003 \001(\010:\005f"
          + "alse:<\n\022method_description\022\036.google.prot"
          + "obuf.MethodOptions\030\320\206\003 \001(\t:8\n\020enum_descr"
          + "iption\022\034.google.protobuf.EnumOptions\030\320\206\003"
          + " \001(\t:C\n\026enum_value_description\022!.google."
          + "protobuf.EnumValueOptions\030\320\206\003 \001(\tB\005H\001\200\001\000"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.DescriptorProtos.getDescriptor(),
            });
    internal_static_NoResponse_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_NoResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_NoResponse_descriptor, new String[] {});
    messageDescription.internalInit(descriptor.getExtensions().get(0));
    forceEmitMessage.internalInit(descriptor.getExtensions().get(1));
    description.internalInit(descriptor.getExtensions().get(2));
    serviceDescription.internalInit(descriptor.getExtensions().get(3));
    serviceExecutionSite.internalInit(descriptor.getExtensions().get(4));
    serviceType.internalInit(descriptor.getExtensions().get(5));
    forceEmitService.internalInit(descriptor.getExtensions().get(6));
    methodDescription.internalInit(descriptor.getExtensions().get(7));
    enumDescription.internalInit(descriptor.getExtensions().get(8));
    enumValueDescription.internalInit(descriptor.getExtensions().get(9));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
